version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:20.04"
    steps:
      - run: apt-get -qq update; apt-get -y install git
      - checkout
      - run:
          name: Installing SUDO
          command: |
            apt-get update
            apt-get install -y sudo
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Installing software-properties-common
          command: |
            sudo apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -y tzdata
            sudo apt-get -y install software-properties-common
      - run:
          name: Install Python
          command:  'sudo -E add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && sudo apt-get -y install build-essential python3'
      - run:
          name: Install Python utilities
          command: 'sudo apt-get install -y python3-dev python3-pip && python3 -m pip install pip --upgrade'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing Boost
          command: 'apt-get install -y libboost-all-dev'
      - run:
          name: Install CMAKE
          command: 'pip install cmake --upgrade'
      - run:
          name: Get NLOpt
          command: 'git clone https://github.com/stevengj/nlopt.git'
      - run:
          name: Create NLOpt folders
          command: 'cd nlopt && mkdir build'
      - run:
          name: Install NLOpt
          command: 'cd nlopt/build/ && cmake .. && make && sudo make install'
      - run:
          name: Install pyscicone
          command: 'cd pyscicone && pip install -e .[test]'
      - run:
          name: Test pyscicone
          command: 'cd pyscicone && python3 -m pytest -s'
      - run:
          name: Creating Debug Build Folder
          command: 'mkdir debug'
      - run:
          name: Running CMAKE
          command: 'cd debug && cmake -DCMAKE_BUILD_TYPE=Debug ../scicone/'
      - run:
          name: Running MAKE
          command: 'cd debug && make VERBOSE=1'
      - run:
          name: Unit Tests (Debug)
          no_output_timeout: 60m
          command: 'cd debug && ./tests 0'
      - run:
          name: Creating Release Build Folder
          command: 'mkdir release'
      - run:
          name: Running CMAKE
          command: 'cd release && cmake -DCMAKE_BUILD_TYPE=Release ../scicone/'
      - run:
          name: Running MAKE
          command: 'cd release && make VERBOSE=1'
      - run:
          name: Unit Tests (Release)
          no_output_timeout: 60m
          command: 'cd debug && ./tests 0'
