name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing Boost
          command: 'apt-get install -y libboost-all-dev'
      - run:
          name: Install CMAKE
          command: 'pip install cmake --upgrade'
      - run:
          name: Get NLOpt
          command: 'git clone https://github.com/stevengj/nlopt.git'
      - run:
          name: Create NLOpt folders
          command: 'cd nlopt && mkdir build'
      - run:
          name: Install NLOpt
          command: 'cd nlopt/build/ && cmake .. && make && sudo make install'
      - run:
          name: Install pyscicone
          command: 'cd pyscicone && pip install -e .[test]'
      - run:
          name: Test pyscicone
          command: 'cd pyscicone && python3 -m pytest -s'
      - run:
          name: Creating Debug Build Folder
          command: 'mkdir debug'
      - run:
          name: Running CMAKE
          command: 'cd debug && cmake -DCMAKE_BUILD_TYPE=Debug ../scicone/'
      - run:
          name: Running MAKE
          command: 'cd debug && make VERBOSE=1'
      - run:
          name: Unit Tests (Debug)
          no_output_timeout: 60m
          command: 'cd debug && ./tests 0'
      - run:
          name: Creating Release Build Folder
          command: 'mkdir release'
      - run:
          name: Running CMAKE
          command: 'cd release && cmake -DCMAKE_BUILD_TYPE=Release ../scicone/'
      - run:
          name: Running MAKE
          command: 'cd release && make VERBOSE=1'
      - run:
          name: Unit Tests (Release)
          no_output_timeout: 60m
          command: 'cd debug && ./tests 0'
